[versions]

#Plugins Versions
agp="9.0.1"
kotlin="2.4.0"
ksp="2.3.9"

#Libraries Versions
composeBom = "2026.06.00"
activityCompose="1.13.0"
lifecycleComposeViewModel="2.8.6"
kotlinExtensions ="1.15.0"
navigationCompose="2.9.8"
kotlinxSerialization ="1.11.0"
workManager ="2.11.2"
dataStore ="1.2.1"
dropBox ="7.0.0"
room="2.8.4"
material3="1.3.0"
javaXL="2.6.12"
javaMail="1.6.8"
googlePlayServices="20.2.0"
googleApiServiceGmail="v1-rev96-1.25.0"
googleApiClientAndroid="1.20.0"
guava="27.0.1-android"

[plugins]
android-application = {id="com.android.application", version.ref="agp"}
kotlin-compose={id="org.jetbrains.kotlin.plugin.compose", version.ref="kotlin"}
kotlin-serialization = {id="org.jetbrains.kotlin.plugin.serialization", version.ref="kotlin"}
kotlin-ksp = {id="com.google.devtools.ksp", version.ref="ksp"}


[libraries]
#Core Libraries
kotlin-extentions={module="androidx.core:core-ktx", version.ref= "kotlinExtensions" }
activity-compose={module="androidx.activity:activity-compose", version.ref="activityCompose"}
viewmodel-compose={module="androidx.lifecycle:lifecycle-viewmodel-compose", version.ref="lifecycleComposeViewModel"}

#Compose BOM
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }

#Navigation
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

#Work Manager
work-manager = { module = "androidx.work:work-runtime-ktx", version.ref = "workManager" }

#Data store
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "dataStore" }

#DropBox
dropbox-core-sdk = { module = "com.dropbox.core:dropbox-core-sdk", version.ref = "dropBox" }
dropbox-android-sdk = { module = "com.dropbox.core:dropbox-android-sdk", version.ref = "dropBox" }

#Room Database
room-complier={module="androidx.room:room-compiler", version.ref="room"}
room-extentions = { module = "androidx.room:room-ktx", version.ref = "room" }

#Material3
material3-core={module="androidx.compose.material3:material3", version.ref="material3"}
material3-window-size ={module="androidx.compose.material3:material3-window-size-class", version.ref="material3"}
material3-adaptive-navigation-suite={module="androidx.compose.material3:material3-adaptive-navigation-suite", version.ref="material3"}

#JXL Library to generate the Microsoft Excel File
java-xl = { module = "net.sourceforge.jexcelapi:jxl", version.ref = "javaXL" }

#Java mail for MIMEMessage creation to send via Gmail
java-mail = { module = "com.sun.mail:android-mail", version.ref = "javaMail" }
java-mail-activation={module="com.sun.mail:android-activation", version.ref="javaMail"}

#Gmail Access
google-play-services-auth={module="com.google.android.gms:play-services-auth", version.ref="googlePlayServices"}
api-client-android={module="com.google.api-client:google-api-client-android", version.ref="googleApiClientAndroid"}
google-api-services-gmail={module="com.google.apis:google-api-services-gmail", version.ref="googleApiServiceGmail"}
guava-android={module="com.google.guava:guava", version.ref="guava"} #needed for conflict resolution of ListenableFuture