import org.jetbrains.kotlin.gradle.dsl.JvmTarget


plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.ksp)
    alias(libs.plugins.kotlin.serialization)
}

android {

    namespace "com.papco.sundar.papcortgs"
    compileSdk = 36

    defaultConfig {
        applicationId "com.papco.sundar.papcortgs"
        targetSdkVersion 36
        minSdkVersion 26
        versionCode 4
        versionName "3.1"
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    packagingOptions {
        resources {
            excludes += 'META-INF/DEPENDENCIES'
            excludes += "META-INF/LICENSE.md"
            excludes += "META-INF/NOTICE.md"
            excludes += "META-INF/LICENSE.txt"
            excludes += "META-INF/NOTICE.txt"
        }
    }


    kotlin {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_17)
        }
    }

}

dependencies {

    //Core Libraries
    implementation(libs.kotlin.extentions)
    implementation(libs.activity.compose)
    implementation(libs.viewmodel.compose)

    // Navigation Library
    implementation(libs.navigation.compose)
    implementation(libs.kotlinx.serialization)

    //WorkManager
    implementation(libs.work.manager)

    //Data Store
    implementation(libs.datastore.preferences)
    
    //Room Database and Lifecycle components
    implementation(libs.room.extentions)
    ksp(libs.room.complier)

    //Dropbox API
    implementation(libs.dropbox.core.sdk)
    implementation(libs.dropbox.android.sdk)

    //Gmail access
    implementation(libs.google.play.services.auth)
    implementation(libs.google.api.services.gmail)
    implementation(libs.api.client.android)
    implementation(libs.guava.android)

    //JXL Library to generate Microsoft Excel file
    implementation(libs.java.xl)

    // JavaMail for Android
    implementation(libs.java.mail)
    implementation(libs.java.mail.activation)

    //Material 3
    implementation(libs.material3.core)
    implementation(libs.material3.window.size)
    implementation(libs.material3.adaptive.navigation.suite)

    //Compose
    // Import the Compose BOM platform first
    implementation(platform(libs.compose.bom))
    implementation(libs.compose.foundation)
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.tooling.preview)
    debugImplementation(libs.compose.ui.tooling)

    //Tests
    testImplementation(libs.junit)
    androidTestImplementation(libs.junit.android)
    androidTestImplementation(libs.espresso.core)

}
